# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='extra_needs',
            field=models.TextField(null=True),
        ),
    ]
