# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161014_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.IntegerField()),
                ('job_title', models.CharField(max_length=512)),
                ('job_description', models.TextField()),
                ('contract_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time')], max_length=128)),
                ('requesting_department', models.CharField(choices=[('administration', 'Administration'), ('service', 'Service'), ('production', 'Production'), ('financial', 'Financial')], max_length=128)),
                ('planning_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_requests', to='app.PlanningRequest')),
            ],
        ),
    ]
