# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_recruitmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentrequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
