# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_recruitmentrequest_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_amount', models.IntegerField()),
                ('reason', models.TextField()),
                ('state', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('denied', 'Denied')], default='new', max_length=15)),
                ('requesting_department', models.CharField(choices=[('administration', 'Administration'), ('service', 'Service'), ('production', 'Production'), ('financial', 'Financial')], max_length=128)),
                ('planning_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_requests', to='app.PlanningRequest')),
            ],
        ),
    ]
