# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161014_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrequest',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('hired', 'Hired'), ('denied', 'Denied')], default='new', max_length=15),
        ),
    ]
