# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161014_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningrequest',
            name='decoration_descr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='planningrequest',
            name='drinks_descr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='planningrequest',
            name='food_descr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='planningrequest',
            name='media_descr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='planningrequest',
            name='parties_descr',
            field=models.TextField(null=True),
        ),
    ]
